### PR TITLE
Refactor Command to UndoableCommand, fix GUI not being undoable

### LINKED ISSUE #138: [PE-D] Actions which were done without the use of cli for e.g clicking the task checkbox to complete it, cannot be undone or redone
No details provided by bug reporter.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: JasonC01/ped#10

### LINKED ISSUE #176: Make every GUI action route through a Command

### PR DESCRIPTION
**Pull request by jeffsieu**
- Fixes bugs where GUI actions are not undoable by replaces every GuiAction with a Command.
- Editing tasks and checking done/undone should now be undoable

Resolves #176
Resolves #138

### CODE REVIEW

File: src/main/java/seedu/address/model/Model.java [hunk 1]
```diff
@@ -192,14 +191,9 @@
      * Replaces the given task {@code target} with {@code editedTask}.
      * {@code target} must exist in the task list.
      * setTask uses targetIndex rather than target Person; This is because tasks may not be unique, unlike persons
```
Comment (koh-jx) [inline src/main/java/seedu/address/model/Model.java:193]: bruh

**Review by koh-jx — APPROVED** [review]
